version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: todo-backend
    container_name: todo-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: todo-frontend
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
